#include <iostream>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <cmath>
#include <algorithm>
#include <vector>
#include <queue>
#include <stack>
#include <set>
#include <map>
#include <unordered_map>
#include <unordered_set>
#include <string>
#include <sstream>
#include <iomanip>
#include <climits>
#include <cassert>
#include <ctime>
#include <cctype>
#include <cstdarg>
#include <bitset>
#include <random>
#include <chrono>
#include <complex>
#include <valarray>
#include <array>
#include <iterator>
#include <functional>
#include <limits>
#include <numeric>
#include <type_traits>
#include <utility>
#include <memory>
#include <tuple>
#include <initializer_list>
#include <fstream>
#include <sstream>


//要不是clang不支持   算了这已经是祖传文件了